// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:46a37b5e-d008-48ed-94ef-94d3382c270f",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_F7BdP5lwq",
    "aws_user_pools_web_client_id": "6u593ta3k21sh2cao2eui57npl",
    "aws_appsync_graphqlEndpoint": "https://vpew6qwn3zftbnrxsnghahadhq.appsync-api.ap-southeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};

const cognitoUser = {
  'x': '52230365David.He'
};


export default awsmobile;
